baseURL = "https://cyheffley.com/"
languageCode = "en-us"
title = "Cy Heffley"
theme = "hugo-imperfect"

[params.intro]
  header    = "Cy Heffley"

  paragraph = "Ramblings of a programmer and musician"

  about     = "Thanks for checking out my page! This is primarily intended as a personal blog. For anyone interested in contacting me about jobs, please see my <a href = \"/about\">About section.</a>"

  # This appears at the top of the sidebar above params.intro.header.
  # A width of less than 100px is recommended from a design perspective.

[params]
    navbarTitle          = "Cy Heffley"

# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item
[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "fa fa-home"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  identifier = "fa fa-id-card-o"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  identifier = "fa fa-newspaper-o"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  identifier = "fa fa-newspaper-o"
  weight = 4

[[menu.main]]
  name = "Papers"
  url = "/papers/"
  identifier = "fa fa-paper-plane-o"
  weight = 5

[[menu.main]]
  name = "Art"
  url = "/art/"
  identifier = "fa fa-paint-brush"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  identifier = "fa fa-envelope-o"
  weight = 7

